# -*- coding: utf-8 -*-
"""VisualisasiAODTiwulan

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k-7QvPjDsCpS49fX3_3aPys_i8ZDiOOP
"""

!pip install rasterio
!pip install matplotlib
!pip install numpy

import rasterio
import matplotlib.pyplot as plt
import matplotlib.colors as colors
import numpy as np

import matplotlib.pyplot as plt
import rasterio
from matplotlib.colors import Normalize
from matplotlib.colors import LinearSegmentedColormap

# Custom color palette
colors = ['black', 'blue', 'purple', 'cyan', 'green', 'yellow', 'red']
n_bins = 100  # Increase or decrease as needed
cmap_name = 'custom'
custom_cmap = LinearSegmentedColormap.from_list(cmap_name, colors, N=n_bins)

# File paths for the TIFF files
dry_season_file = '/content/drive/MyDrive/AOD20N21/AOD_Jakarta_JanMar_2020_2021.tif'
wet_season_file = '/content/drive/MyDrive/AOD20N21/AOD_Jakarta_AprJun_2020_2021.tif'
jul_sep_season_file = '/content/drive/MyDrive/AOD20N21/AOD_Jakarta_JulSep_2020_2021.tif'
oct_dec_season_file = '/content/drive/MyDrive/AOD20N21/AOD_Jakarta_OctDec_2020_2021.tif'

# Open the TIFF files using rasterio and read the first band
with rasterio.open(dry_season_file) as src:
    dry_data = src.read(1)
with rasterio.open(wet_season_file) as src:
    wet_data = src.read(1)
with rasterio.open(jul_sep_season_file) as src:
    jul_sep_data = src.read(1)
with rasterio.open(oct_dec_season_file) as src:
    oct_dec_data = src.read(1)

# Creating normalization for the colormap
norm = Normalize(vmin=0, vmax=400)

# Function to format the colorbar labels
def format_cbar_labels(x, pos):
    if x >= 400:
        return ">0.4"
    else:
        return f"{x/1000:.3f}"

# Plotting the heatmaps with larger titles
fig, axes = plt.subplots(2, 2, figsize=(18, 15), sharex=True, sharey=True)

title_fontsize = 20  # Set the title font size

axes[0, 0].imshow(dry_data, cmap=custom_cmap, norm=norm)
axes[0, 0].set_title('Januari-Maret 2020-2021', fontsize=title_fontsize)
axes[0, 0].axis('off')

axes[0, 1].imshow(wet_data, cmap=custom_cmap, norm=norm)
axes[0, 1].set_title('April-Juni 2020-2021', fontsize=title_fontsize)
axes[0, 1].axis('off')

axes[1, 0].imshow(jul_sep_data, cmap=custom_cmap, norm=norm)
axes[1, 0].set_title('Juli-September 2020-2021', fontsize=title_fontsize)
axes[1, 0].axis('off')

axes[1, 1].imshow(oct_dec_data, cmap=custom_cmap, norm=norm)
axes[1, 1].set_title('Oktober-Desember 2020-2021', fontsize=title_fontsize)
axes[1, 1].axis('off')

# Adding a colorbar with formatted labels
cbar_ax = fig.add_axes([0.15, 0.05, 0.7, 0.025])  # x, y, width, height
cbar = fig.colorbar(plt.cm.ScalarMappable(norm=norm, cmap=custom_cmap), cax=cbar_ax, orientation='horizontal', format=plt.FuncFormatter(format_cbar_labels))

plt.show()